
# docker-compose.yml

services:
  # MongoDB
  mongodb:
    image: mongo:7
    container_name: agrimon_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: AGRIMON
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Redis
  redis:
    image: redis:8
    container_name: agrimon_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  # PostgreSQL
  postgres:
    image: postgres:16
    container_name: agrimon_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Backend
  backend:
    build: ./backend
    container_name: agrimon_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
      - postgres
      
  # Frontend
  frontend:
    build: ./frontend
    container_name: agrimon_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"

volumes:
  mongo_data:
  pgdata:
  



# docker-compose down
# docker-compose up -d
# docker-compose up -d --build

# docker-compose logs -f backend
# docker-compose up -d --build backend(after updating .env)
# docker-compose up -d backend

# docker-compose stop backend
# docker-compose rm backend
# docker-compose up -d backend
# docker-compose ps

# git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git
